
# general settings
name: train_DinoATDUnet_SRx4_sratch
model_type: SRUNetModel
scale: 4
num_gpu: 1
manual_seed: 0
# find_unused_parameters: True

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/DF2K/train_HR
    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/DF2K/train_LR_bicubic/X4
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: True
    persistent_workers: True

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/test/Set5/image_SRF_4/HR
    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/test/Set5/image_SRF_4/LR
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/test/Set14/image_SRF_4/HR
    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/test/Set14/image_SRF_4/LR
    io_backend:
      type: disk

# network structures
network_g:
  type: Dino_ATD_UNet
  # ConvNeXt-Tiny UNet with Memory Enhancement for super-resolution
  input_channels: 3
  img_size: 256
  output_channels: 3
  encoder_type: tiny
  drop_path_rate: 0.0
  # Decoder settings
  num_res_blocks: 1
  attn_resolutions: [16, 8]
  dropout: 0.0
  resamp_with_conv: true
  meanflow: false
  scale_factor_first_layer: 2
  check_point: ~
  freeze_backbone: false
  use_atd: true
  atd_num_tokens: 512
  atd_reducted_dim: 16
  atd_num_heads: 4
  atd_category_size: 256
  atd_dim_ffn_td: 16
  atd_convffn_kernel_size: 5
  atd_mlp_ratio: 2
  # Feature refine
  use_feature_refine: true
  fr_depths: [6,6,6,6,6,6]
  fr_num_heads: [4,4,4,4,4,4]
  fr_window_size: 16
  fr_num_tokens: 512
  fr_reducted_dim: 16
  fr_dim_ffn_td: 16
  fr_category_size: 256
  fr_convffn_kernel_size: 5
  fr_mlp_ratio: 2

# path
path:
  pretrain_network_g: ~ #experiments/000_ATD_SRx2_scratch/models/net_g_latest.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  use_fp16: true
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.9]

  scheduler:
    type: MultiStepLR
    milestones: [ 250000, 400000, 450000, 475000 ]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: yes
    
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 4
      test_y_channel: yes
    lpips:
      type: calculate_lpips
      model: 'alex'

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
