# general settings
name: meanflowSR
model_type: MeanFlowModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode, using 1 for single GPU debugging
manual_seed: 0

# network structures
network_g:
  type: DiT
  input_size: 128
  patch_size: 4
  in_channels: 3
  dim: 384
  depth: 12
  num_heads: 16
  mlp_ratio: 4.0
  num_register_tokens: 4
  num_classes: ~

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [250000, 250000, 250000, 250000]
    restart_weights: [1, 1, 1, 1]
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

# dataset and data loader settings
datasets:
  train:

    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/DF2K/train_HR
    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/DF2K/train_LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/Set5/GTmod12
    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/Set5/LRbicx4
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/Set14/GTmod12
    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/Set14/LRbicx4
    filename_tmpl: '{}'
    io_backend:
      type: disk
#  val_3:
#    name: Urban100
#    type: PairedImageDataset
#    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/Urban100/image_SRF_4/HR
#    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/Urban100/image_SRF_4/LR
#    filename_tmpl: '{}'
#    io_backend:
#      type: disk
#  val_4:
#    name: BSDS100
#    type: PairedImageDataset
#    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/BSDS100/image_SRF_4/HR
#    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/BSDS100/image_SRF_4/LR
#    filename_tmpl: '{}'
#    io_backend:
#      type: disk
#  val_5:
#    name: Manga109
#    type: PairedImageDataset
#    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/Manga109/image_SRF_4/HR
#    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/Manga109/image_SRF_4/LR
#    filename_tmpl: '{}'
#    io_backend:
#      type: disk