# general settings
#swinflowir上采样倍率为1，测试噪声为输入，LR图像为reference,噪声和LR cat在一起。
name: train_PFM_DiT_B8_SRx8_P256_github_pfm_source
datasets:
  train:
    task: SR
    name: DF2K
    type: SFMPairedImageDataset #ModifiedPairedImageDataset
    scale: 8
    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/DF2K/train_HR
    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/DF2K/train_LR_bicubic/X8
    filename_tmpl: '{}x8'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 100
    prefetch_mode: ~
  val_1:
    name: Set5
    type: SFMPairedImageDataset
    scale: 8
    gt_size: 256
    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/test/Set5/image_SRF_8/HR
    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/test/Set5/image_SRF_8/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk

# dist training settings
dist_params:
  backend: nccl
  port: 29500
