name: flow_matching
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python>=3.9
  - pytorch
  - pytorch-cuda
  - matplotlib
  - jupyter
  - numpy
  - pip
  - tqdm
  - pip:
    - pre-commit
    - black>=22.6.0
    - usort>=1.0.4
    - ufmt>=2.3.0
    - flake8>=7.0.0
    - ipykernel
    - torchdiffeq
    - scikit-learn
    - pydoclint
    - coverage
