# general settings
name: train_DinoUNet_Fix_Encoder_SRx4_scratch_P64B8_DF2K_500k
model_type: SRUNetModel
scale: 4
num_gpu: 1
manual_seed: 0

# network structures
network_g:
  type: ConvNeXtUNet
  # ConvNeXt-Tiny UNet for super-resolution
  input_channels: 3
  img_size: 256
  output_channels: 3
  dims: [96, 192, 384, 768]
  depths: [3, 3, 9, 3]
  drop_path_rate: 0.0
  # Decoder settings
  num_res_blocks: 2
  attn_resolutions: [16, 8]
  dropout: 0.0
  resamp_with_conv: true
  meanflow: false
  # Encoder pretrained weights
  pretrained: /8T2/pretrained_models/DINOV3_pretrained_weight/ConvNeXt/dinov3_convnext_tiny_pretrain_lvd1689m-21b726bb.pth
  freeze_backbone: true

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true
  pbar: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true
    lpips:
      type: calculate_lpips
      model: 'alex'

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/DF2K/train_HR
    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/DF2K/train_LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/test/Set5/image_SRF_4/HR
    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/test/Set5/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: /8T1/dataset/SRDataset/ImageSR/test/Set14/image_SRF_4/HR
    dataroot_lq: /8T1/dataset/SRDataset/ImageSR/test/Set14/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
