# general settings
name: 204_EDSR_Lx2_f256b32_DIV2K_300k_B16G1_wandb
model_type: SRModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# network structures
network_g:
  type: EDSR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 256
  num_block: 32
  upscale: 2
  res_scale: 0.1
  img_range: 255.
  rgb_mean: [0.4488, 0.4371, 0.4040]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/DF2K/train_HR
    dataroot_lq: datasets/DF2K/train_LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/DIV2Kdatasets/benchmark/Set5/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Set5/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_2:
    name: Set14
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/Set14/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Set14/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_3:
    name: Urban100
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/Urban100/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Urban100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_4:
    name: BSDS100
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/BSDS100/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/BSDS100/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk
  val_5:
    name: Manga109
    type: PairedImageShuffleDataset
    dataroot_gt: datasets/benchmark/Manga109/image_SRF_4/HR
    dataroot_lq: datasets/benchmark/Manga109/image_SRF_4/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk